### ISSUE TITLE
Not working for android in Nativescript 4.1.2

### ISSUE THREAD

**Issue by atchakraborty** [Essent/nativescript-adobe-marketing-cloud#24]
Hi,
Previously this plugin was working with 3.4 Nativescript version for android and iOS. But upgrading to 4.1.2 causing issue for android. Adobe analytics stopped working.

System information:
√ Component nativescript has 4.1.2 version and is up to date.
√ Component tns-core-modules has 4.1.1 version and is up to date.
√ Component tns-android has 4.1.3 version and is up to date.
√ Component tns-ios has 4.1.1 version and is up to date.

So I decided to update it to plugin latest **Version 1.5.1**. But can't install nativescript-adobe-marketing-cloud@1.5.1 

Error I am getting:

> npm ERR! notarget No matching version found for nativescript-adobe-marketing-cloud@1.5.1

So please save my life!!!!

**Comment by dennis-montana** [comment]
There was an issue which caused version 1.5.1 to never be published to NPM, we now have a new version with support for NativeScript 5.1.

**Comment by wytzen** [comment]
The 1.6.0 version is not likely to solve your problem. the SDK behind the plugin crashes on android if tracking calls are made to the plugin before setContext is done. One solution is to add a check to see if setContext was done or not before allowing any calls.
