### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by fpaaske** [Essent/nativescript-adobe-marketing-cloud#30]
After submitting an app with this plugin we get this warning:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I assume this is because the native library from Adobe contains some reference to it, so it might be solved by issue #28

**Comment by mrpaaske** [comment]
@spike1292 @jboeijenga  @evanrooijen Not sure if anyone get the notifications on issues, so I'm just mentioning you guys here :-) Sorry for nagging.

I did a quick test by replacing the `AdobeMobileLibrary.a` in node_modules with the latest one (v4.19), and now the processing warning went away (seems to have been fixed by Adobe in iOS SDK v4.18.8).

I could help by submitting a PR with the updated libraries (at least for iOS), but I don't really know how.

**Comment by mrpaaske** [comment]
Any update on this issue?

**Comment by spike1292** [comment]
Hi @mrpaaske, Currently i'm not on the mobile team anymore.
@b-ivanovic @nvukovic @djstojanovic can you take a look?

**Comment by spike1292** [comment]
> @spike1292 @jboeijenga @evanrooijen Not sure if anyone get the notifications on issues, so I'm just mentioning you guys here :-) Sorry for nagging.
> 
> I did a quick test by replacing the `AdobeMobileLibrary.a` in node_modules with the latest one (v4.19), and now the processing warning went away (seems to have been fixed by Adobe in iOS SDK v4.18.8).
> 
> I could help by submitting a PR with the updated libraries (at least for iOS), but I don't really know how.

A good start is looking at https://docs.nativescript.org/plugins/plugin-reference
As you are suggestion replacing the native library for android and ios is always a good start ;)
Next step should be updating the types, new nativescript cli should help with it:
- ios, see https://docs.nativescript.org/plugins/Use-Native-iOS-Libraries#generating-typescript-typings
- android, see https://docs.nativescript.org/core-concepts/android-runtime/metadata/generating-typescript-declarations

with the new types you can possibly spot api differences, but you should take a look at the adobe changelog to be sure if there aren't any breaking api changes.

i hope this will get you on track

**Comment by b-ivanovic** [comment]
> Hi @mrpaaske, Currently i'm not on the mobile team anymore.
> @b-ivanovic @nvukovic @djstojanovic can you take a look?

Hi @spike1292,

We will talk to our product owner about this and will try to convince her to pick this one in our next sprint. As far as I can see, there is no exact date when Apple will start rejecting the builds because of this, that makes harder prioritizing this one.
If anyone else finds some time to fix this, we will review and accept the merge request.

**Comment by mrpaaske** [comment]
This just got a bit more urgent:

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

@b-ivanovic Did you get this prioritized? :)

**Comment by b-ivanovic** [comment]
It's planned for our next PI which ends at end of August. The decision is based on the information that Apple will be accepting existing applications with UIWebView until December this year. We still don't know when exactly it will be picked up within this period (could be in 2 weeks or in 3 months). I'll try to push it.

**Comment by mrpaaske** [comment]
Thank you, we haven't launched our app yet, so this is currently blocking us. Thanks for helping!

**Comment by fpaaske** [comment]
@b-ivanovic do you have any updates on this issue?

**Comment by b-ivanovic** [comment]
We updated the code to use the latest SDK, it's pushed to master branch. It's now released under different name on npmjs. You can find it here: https://www.npmjs.com/package/@essent/nativescript-adobe-experience-cloud.

**Comment by fpaaske** [comment]
Thanks, @b-ivanovic, that's great news! Is the new repo available as well?

**Comment by b-ivanovic** [comment]
No problem!
