### ISSUE TITLE
Cannot find namespace 'android'

### ISSUE THREAD

**Issue by kbajjuri** [Essent/nativescript-adobe-marketing-cloud#8]
Compilation failing with missing android reference at 
`/nativescript-adobe-marketing-cloud/adobe-analytics.common.ts(15,52): error TS2503: Cannot find namespace 'android'.`

I tried to run the demo from here and it was throwing the same error.

Am I missing anything to run this plugin?

**Comment by kbajjuri** [comment]
`abstract setContext(applicationContext: android.content.Context): void;
  abstract collectLifecycleData(activity: android.app.Activity, debugLogging?: boolean): void;`

Changing the above lines to following seems to be working, needs to test more on this.
`abstract setContext(applicationContext: any): void;
abstract collectLifecycleData(activity: any, debugLogging?: boolean): void;
`

**Comment by corne-de-bruin** [comment]
Hi @kbajjuri,

Sorry for the late respons.
The android typings should be part of the tns-platform-declarations and are included in the references.d.ts.

If you still run into this issue, maybe you could verify if tns-platform-declarations is installed in your node_modules directory?

**Comment by corne-de-bruin** [comment]
Hi @kbajjuri ,

I've just released a new version of this plugin (1.5.0) this should solve your issue.
