### ISSUE TITLE
Obtain visitorID

### ISSUE THREAD

**Issue by ao1ansal** [Essent/nativescript-adobe-marketing-cloud#9]
I would like to fetch the 'visitorID' from this module for both iOS and Android similar to what have been described in the blog https://theblog.adobe.com/hybrid-apps-making-whole-two-halves/ . They are actually fetching the userIdentifier/trackingIdentifier and setting it as the visitorID value. @corne-de-bruin @spike1292  @code0wl  @jboeijenga @dennis-montana

**Comment by spike1292** [comment]
Hi @ao1ansal,
If have read the blog and it looks similar to https://marketing.adobe.com/resources/help/en_US/mobile/ios/hybrid_app.html
Could this also help in your situation?

**Comment by StevenLJackson1** [comment]
Hey @ao1ansal,

I created a PR to address this.  @spike1292 can approve it and merge it in when he has the time.

Steve
P.S. Happy early birthday!

**Comment by spike1292** [comment]
The pr looks good but I have a question for one of my colleagues. But he is celebrating carnival. When he is back I will merge the pr!

**Comment by spike1292** [comment]
Hi @ao1ansal & @StevenLJackson1,

Just sat down with my colleague @corne-de-bruin. We will merge pr #10, but currently we can't release a new version. This is because this repository needs to be migrated to the [new nativescript plugin seed](https://github.com/NativeScript/nativescript-plugin-seed). Without this change you get the following error message when you run `npm run demo.ios`

```
Found peer TypeScript 2.3.4
Preparing project...
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Unable to apply changes on device: 1560833F-C624-43F4-8794-1549C5776097. Error is: Processing node_modules failed. Error: cp: cannot create directory '/Users/henk/Projects/Essent/nativescript-adobe-marketing-cloud/demo/platforms/ios/demo/app/tns_modules': No such file or directory.
```

**Comment by StevenLJackson1** [comment]
Yes, I'm seeing that right now as I'm trying to run the demo.  If I downgrade the {N} CLI does that fix things temporarily until #12 is fixed?

**Comment by corne-de-bruin** [comment]
Hi @StevenLJackson1 

I've noticed the same with older versions. I'm currently started to migrate the plugin to the new nativescript-plugin-seed structure see: https://github.com/NativeScript/nativescript-plugin-seed

After that we plan to update the Adobe SDK's.

We hope to solve this issue by taking these steps.

**Comment by StevenLJackson1** [comment]
Thank you @corne-de-bruin, I see that you updated the project to support the new nativescript-plugin-seed structure and newer NativeScript version!

Does this mean a release will be coming soon, as well?

**Comment by corne-de-bruin** [comment]
Hi @ao1ansal  and @StevenLJackson1 ,

I've just created a new release of this plugin (1.5.0) which includes this feature request.
